/**
 * Write orchestration — the multi-call sequences the `sense` / decline commands
 * invoke. They route every write through {@link GitHubPort}, so the sequence
 * logic is unit-testable with a fake port (Phase-1 plan, design rule 1).
 *
 * The pure content (PR title/body) is extracted into {@link buildProposalContent}.
 */

import type { Descriptor } from "./types";
import type { GitHubPort } from "./ports";
import type { ProvenanceStub } from "./provenance";
import {
  parseProvenanceStub,
  primarySource,
  provenanceFile,
  serializeProvenanceStub,
  withVerification,
} from "./provenance";
import type { DeclineInput } from "./decline";
import { declineFile } from "./decline";
import { branchFor, labelFor, provenancePathFor } from "./descriptor";

export interface ProposeInput {
  descriptor: Descriptor;
  provenance: ProvenanceStub;
  /** Extra files to commit on the branch (e.g. a placeholder artifact). */
  artifacts?: ReadonlyArray<{ path: string; content: string }>;
}

export interface ProposeResult {
  prNumber: number;
  branch: string;
}

/** Phase-1 PR content: a templated impact-declaration stub (prose is a later phase). */
export function buildProposalContent(input: ProposeInput): { title: string; body: string } {
  const { descriptor, provenance } = input;
  const title = `data: ${descriptor}`;
  // One source reads as a single line; several get named so a reviewer can see
  // what the edition actually rests on.
  const sourceLines =
    provenance.sources.length === 1
      ? [`- **Source:** ${primarySource(provenance)}`]
      : ["- **Sources:**", ...provenance.sources.map((s) => `  - \`${s.id}\` — ${s.resource}`)];
  const body = [
    `## New data: ${descriptor}`,
    "",
    ...sourceLines,
    `- **Retrieved:** ${provenance.retrievedAt}`,
    `- **Hash:** \`${provenance.hash}\``,
    ...(provenance.generated ? [`- **Generated by:** \`${provenance.generated.by}\``] : []),
    "",
    "_Impact declaration: prose interpretation is a later phase; this is a templated stub._",
    "",
  ].join("\n");
  return { title, body };
}

export async function proposeDataPR(port: GitHubPort, input: ProposeInput): Promise<ProposeResult> {
  const { descriptor } = input;
  const base = await port.defaultBranch();
  const fromSha = await port.branchHeadSha(base);
  const branch = branchFor(descriptor);
  await port.createBranch(branch, fromSha);

  const files = [provenanceFile(input.provenance), ...(input.artifacts ?? [])];
  for (const file of files) {
    await port.putFile({
      branch,
      path: file.path,
      content: file.content,
      message: `data(${descriptor}): add ${file.path}`,
    });
  }

  const { title, body } = buildProposalContent(input);
  const prNumber = await port.openPullRequest({ head: branch, base, title, body });
  await port.addLabels(prNumber, [labelFor(descriptor)]);
  return { prNumber, branch };
}

export interface VerificationInput {
  descriptor: Descriptor;
  /** Whoever merged the data-PR, in the OKF actor grammar. */
  by: string;
  /** ISO-8601 timestamp of the merge. */
  at: string;
}

/**
 * Record the human merge as a `verified` entry on the edition's own provenance
 * stub — the accepted record's existing home for it (CONCEPT.md → Interop).
 *
 * Written *at merge* rather than derived at export time on purpose: a bundle
 * whose trust tier depends on whether the exporter happened to hold a token
 * would be worse than one with no tier at all, and deriving it would cost
 * `okf-export` its no-token, offline property. The symmetry is with
 * {@link recordDecline} — the loop has always recorded rejection and never
 * acceptance.
 *
 * Fails loudly when the stub is missing. A merge we cannot attach to an edition
 * is a broken instance, and silence is exactly how a decline path already went
 * wrong once.
 */
export async function recordVerification(
  port: GitHubPort,
  input: VerificationInput,
): Promise<{ recorded: boolean }> {
  const base = await port.defaultBranch();
  const path = provenancePathFor(input.descriptor);
  const json = await port.readFileFromRef(base, path);
  if (json === null) {
    throw new Error(
      `Cannot record verification for ${input.descriptor}: ${path} is not on ${base}`,
    );
  }

  const stub = parseProvenanceStub(json);
  const updated = withVerification(stub, { by: input.by, at: input.at });
  if (updated === stub) return { recorded: false };

  await port.putFile({
    branch: base,
    path,
    content: serializeProvenanceStub(updated),
    message: `verify(${input.descriptor}): record merge`,
  });
  return { recorded: true };
}

export async function recordDecline(port: GitHubPort, input: DeclineInput): Promise<void> {
  const base = await port.defaultBranch();
  const file = declineFile(input);
  await port.putFile({
    branch: base,
    path: file.path,
    content: file.content,
    message: `decline(${input.descriptor}): record reason`,
  });
}
