/**
 * `continuous-research init` scaffolding (Phase-1 plan, design rule 3: the CLI
 * only scaffolds; credential / identity / App setup stays documented manual
 * steps). Pure — returns the files to write; the I/O wrapper in `cli.ts`
 * writes them, skipping any that already exist.
 *
 * The templates mirror the configuration PROVEN in continuous-research-sample
 * (2026-07-02): data-PRs are opened under a GitHub App identity (default-token
 * PRs cannot trigger the gh-aw interpretation workflow), and interpretation is
 * a gh-aw agentic workflow the instance compiles with `gh aw compile`.
 *
 * `\${{ ... }}` in the templates is escaped so it survives as a literal GitHub
 * Actions expression, not a TS interpolation.
 */

export interface ScaffoldFile {
  path: string;
  content: string;
}

const CONFIG = `{
  "sensor": "node sensor.mjs"
}
`;

const SENSE_WORKFLOW = `name: sense

# Generated by \`continuous-research init\`.
on:
  workflow_dispatch:
  # Uncomment once your sensor is wired; match the cadence to your data's
  # real rhythm (the engine's dedup makes re-runs safe at any frequency):
  # schedule:
  #   - cron: "30 0 * * *"

# Serialize runs so two can't both see "new" and double-propose.
concurrency:
  group: sense
  cancel-in-progress: false

# The engine writes with the App token below — data-PRs must be App-authored
# so they can trigger the gh-aw interpretation workflow (default-token PRs
# don't trigger downstream workflows). The workflow's own token stays
# read-only.
permissions:
  contents: read

jobs:
  sense:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Mint App installation token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: \${{ secrets.APP_ID }}
          private-key: \${{ secrets.APP_PRIVATE_KEY }}
      - name: sense
        env:
          GITHUB_TOKEN: \${{ steps.app-token.outputs.token }}
        # If the framework is not reachable via npx in your setup, vendor the
        # engine bundle into the repo and use:
        #   run: node engine/continuous-research.mjs sense
        run: npx --yes github:norabble/continuous-research sense
`;

const DECLINE_WORKFLOW = `name: decline

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  record-decline:
    # Only closed-unmerged data-PRs (the engine also no-ops defensively).
    if: >-
      github.event.pull_request.merged == false &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'data:')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: record-decline
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: npx --yes github:norabble/continuous-research record-decline
`;

const INTERPRETATION_WORKFLOW = `---
description: "Interpretation step: write the impact declaration for a new data edition onto its data-PR"
on:
  pull_request:
    types: [opened, reopened]
  bots:
    # TODO: your GitHub App's slug — the author of the engine's data-PRs.
    - your-app-slug
engine:
  # Engine/model are per-instance choices. This pairing is proven against
  # free-tier quotas (~16–25 API requests per session; smaller "lite"-class
  # models below gemini-3.1-flash-lite have failed the harness protocol).
  id: gemini
  model: gemini-3.1-flash-lite
timeout-minutes: 15
permissions:
  contents: read
  pull-requests: read
safe-outputs:
  push-to-pull-request-branch:
    # The interpretation contract: the agent may touch ONLY the impact
    # declaration and the living findings doc. allowed-files is the binding
    # constraint; protected-files must be 'allowed' because .research/ is a
    # top-level dot-folder, which the default 'blocked' policy rejects even
    # for allowlisted paths.
    protected-files: allowed
    allowed-files:
      - ".research/impact/*.md"
      - "findings.md"
---

# Interpretation step

You are the **interpretation step** of a Continuous Research instance. A
data-PR proposing a new data edition has just been opened. Your job is to
write the **impact declaration**: what the new edition means for the existing
claims.

## Guard

First check the triggering pull request's labels. If it has no label starting
with \`data:\`, stop immediately and do nothing. Otherwise, the part after
\`data:\` is the **descriptor**.

## Read

Check out the PR's branch. Read:

1. TODO: the new edition's artifact(s) for this project — describe where the
   sensor/pipeline writes them, e.g. \`data/<source>/<descriptor>.json\`.
2. \`findings.md\` — the living prose. Each claim paragraph is followed by an
   invisible HTML-comment annotation. Its inner content has this form (the
   line in the file is wrapped as an HTML comment):

   \`\`\`text
   claim: <id> | backs: <result keys> | status: <status>
   \`\`\`

## Write

On the PR branch, make exactly two changes:

1. **Create \`.research/impact/<descriptor>.md\`** — the impact declaration:
   - **Prior claim** — quote the current claim and its status.
   - **What changed** — the new edition's values vs. the ones in the prose.
   - **Assessment** — one of **strengthened / weakened / overturned**, with a
     short justification. Distinguish one-off moves from real changes; do not
     overclaim.
   - **Revised claim** — the new claim text.
2. **Update \`findings.md\`** — replace the claim paragraph with the revised
   claim (keep the same claim id in the annotation; update the values, the
   edition reference, and the \`status\` field as assessed).

Keep the tone factual and appropriately hedged. Commit both files to the PR
branch with the message \`interpretation(<descriptor>): impact declaration\`.
`;

export const NEXT_STEPS = `
Next steps:
  1. Sensor: point .research/config.json "sensor" at a command that prints a
     detection-result JSON on stdout, and writes artifacts to the working tree.
  2. GitHub App (required): create an App (permissions: Contents, Issues, and
     Pull requests — read & write), install it on this repo, and set the
     APP_ID and APP_PRIVATE_KEY secrets. Data-PRs must be App-authored, or the
     interpretation workflow never triggers.
  3. Interpretation: fill in the TODOs in
     .github/workflows/interpretation.md, set your inference secret (e.g.
     GEMINI_API_KEY), then compile it:
       gh extension install github/gh-aw && gh aw compile
  4. Commit .research/ and .github/workflows/ (including the compiled
     interpretation.lock.yml), then dispatch the "sense" workflow.
`;

export function scaffoldFiles(): ScaffoldFile[] {
  return [
    { path: ".research/config.json", content: CONFIG },
    { path: ".github/workflows/sense.yml", content: SENSE_WORKFLOW },
    { path: ".github/workflows/decline.yml", content: DECLINE_WORKFLOW },
    { path: ".github/workflows/interpretation.md", content: INTERPRETATION_WORKFLOW },
  ];
}
