/**
 * `continuous-research init` scaffolding (Phase-1 plan, design rule 3: the CLI
 * only scaffolds; credential / identity / App setup stays documented manual
 * steps). Pure — returns the files to write; the I/O wrapper in `cli.ts`
 * writes them, skipping any that already exist.
 *
 * The templates mirror the configuration PROVEN in continuous-research-sample
 * (2026-07-02): data-PRs are opened under a GitHub App identity (default-token
 * PRs cannot trigger the gh-aw interpretation workflow), and interpretation is
 * a gh-aw agentic workflow the instance compiles with `gh aw compile`.
 *
 * `\${{ ... }}` in the templates is escaped so it survives as a literal GitHub
 * Actions expression, not a TS interpolation.
 */

export interface ScaffoldFile {
  path: string;
  content: string;
}

const CONFIG = `{
  "sensor": "node sensor.mjs",
  "site": { "enabled": false, "title": "TODO: your project title" }
}
`;

const SENSE_WORKFLOW = `name: sense

# Generated by \`continuous-research init\`.
on:
  workflow_dispatch:
  # Uncomment once your sensor is wired; match the cadence to your data's
  # real rhythm (the engine's dedup makes re-runs safe at any frequency):
  # schedule:
  #   - cron: "30 0 * * *"

# Serialize runs so two can't both see "new" and double-propose.
concurrency:
  group: sense
  cancel-in-progress: false

# The engine writes with the App token below — data-PRs must be App-authored
# so they can trigger the gh-aw interpretation workflow (default-token PRs
# don't trigger downstream workflows). The workflow's own token stays
# read-only.
permissions:
  contents: read

jobs:
  sense:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "24" # npm 11: npm 10 (node 22) cannot install commit-pinned git deps
      - name: Mint App installation token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: \${{ secrets.CONTINUOUS_RESEARCH_APP_ID }}
          private-key: \${{ secrets.CONTINUOUS_RESEARCH_APP_PRIVATE_KEY }}
          # Downscope to the sensing loop's needs: push data branches, open
          # data-PRs, file/lock the drift issue.
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - name: sense
        env:
          GITHUB_TOKEN: \${{ steps.app-token.outputs.token }}
        # If the framework is not reachable via npx in your setup, vendor the
        # engine bundle into the repo and use:
        #   run: node engine/continuous-research.mjs sense
        run: npx --yes github:norabble/continuous-research#v0.1.6 sense
      - name: Escalate drift
        # If the sensor wrote .research/drift/report.json (working-tree
        # only), file/refresh the single LOCKED sensor-drift issue the
        # repair workflow consumes. No report -> no-op.
        env:
          GITHUB_TOKEN: \${{ steps.app-token.outputs.token }}
        run: npx --yes github:norabble/continuous-research#v0.1.6 escalate-drift
`;

const DECLINE_WORKFLOW = `name: decline

on:
  pull_request:
    types: [closed]

# The decline record lands on main. If main carries a ruleset, GITHUB_TOKEN
# can never bypass it — the App can. The workflow's own token stays
# read-only either way.
permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  record-decline:
    # Only closed-unmerged data-PRs (the engine also no-ops defensively).
    if: >-
      github.event.pull_request.merged == false &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'data:')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "24" # npm 11: npm 10 (node 22) cannot install commit-pinned git deps
      - name: Mint App installation token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: \${{ secrets.CONTINUOUS_RESEARCH_APP_ID }}
          private-key: \${{ secrets.CONTINUOUS_RESEARCH_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-issues: read
          permission-pull-requests: read
      - name: record-decline
        env:
          GITHUB_TOKEN: \${{ steps.app-token.outputs.token }}
        run: npx --yes github:norabble/continuous-research#v0.1.6 record-decline
`;

const SITE_WORKFLOW = `name: site

# Generated by \`continuous-research init\`. Enable: set site.enabled=true in
# .research/config.json and turn on Pages (Settings → Pages → source "GitHub
# Actions").
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]
    paths: ["findings.md", ".research/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: site
  cancel-in-progress: true

jobs:
  build-deploy:
    # PR events matter only for data-PRs (the pending-updates section);
    # pushes to main and manual dispatch always rebuild.
    if: >-
      github.event_name != 'pull_request' ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'data:')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: github-pages
      url: \${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "24" # npm 11: npm 10 (node 22) cannot install commit-pinned git deps
      - name: build
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: npx --yes github:norabble/continuous-research#v0.1.6 site
      # Inlined the official Pages-upload composite action: it calls
      # actions/upload-artifact by tag internally, which repos enforcing
      # required SHA pinning reject (the policy applies to nested
      # references). These two steps are what that composite does, minus its .git/.github/
      # dotfile excludes — _site/ is generator output, so there is nothing to exclude.
      - name: Package site for Pages
        if: hashFiles('_site/**') != ''
        run: tar --dereference --hard-dereference -cvf "$RUNNER_TEMP/artifact.tar" -C _site .
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: hashFiles('_site/**') != ''
        with:
          name: github-pages
          path: \${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error
      - id: deploy
        if: hashFiles('_site/**') != ''
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
`;

const SENSOR_REPAIR_WORKFLOW = `name: sensor-repair

# OPTIONAL — Claude Code integration (delete this file if you don't use it).
# Generated by \`continuous-research init\`. The framework is engine-
# agnostic; this workflow is a documented integration with
# anthropics/claude-code-action, proven on continuous-research-sample.
#
# Agentic code fix for sensor drift, split into two jobs so the agent never
# holds a write-capable token:
#   repair — the agent researches a replacement source and edits the sensor
#            in the working tree (read-only GITHUB_TOKEN), then leaves its
#            fix as an uploaded artifact (patch + PR text).
#   ship   — deterministic: re-applies the patch (sensor file only,
#            enforced mechanically), re-runs tests, then pushes the branch
#            and opens/updates the PR with a freshly minted, downscoped App
#            token. "Re-run failed jobs" retries ship without a new agent
#            run.
# The agent reads untrusted content (the drift issue, live API responses)
# with open egress, so nothing in its environment may be worth stealing.
on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Open sensor-drift issue number to repair against"
        required: true

permissions:
  contents: read

concurrency:
  group: sensor-repair
  cancel-in-progress: false

jobs:
  repair:
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'sensor-drift'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          # No credentials in .git/config for the agent's Bash to find.
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"
      - uses: anthropics/claude-code-action@0fe28cdb64e23015219b0e478100b7105fd7dfa1 # v1
        with:
          claude_code_oauth_token: \${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Read-only, passed explicitly: otherwise the action mints a
          # token from a Claude App installation, which may carry write
          # scopes — exactly what this two-job structure exists to avoid.
          github_token: \${{ secrets.GITHUB_TOKEN }}
          # TODO: your GitHub App's slug — the actor that labels drift
          # issues. Never "*" on a public repo.
          allowed_bots: "your-app-slug"
          claude_args: |
            --max-turns 40
            --allowedTools "Read,Glob,Grep,Edit,Write,WebFetch,Bash(curl:*),Bash(node:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(gh issue view:*)"
          prompt: |
            You are the sensor-repair agent for this Continuous Research
            instance. Drift issue: #\${{ github.event.issue.number || inputs.issue_number }}.

            Read that issue first (the drift report is embedded in it),
            then the sensor and its config.
            TODO: list your instance's sensor file(s) and any constraint
            files the agent must respect (e.g. a source blocklist), and
            name a few candidate replacement sources to evaluate first.

            Task: the sensor's declared source is unusable. Find a usable
            replacement source, verify it by actually fetching it and
            inspecting the real response, then edit the sensor file ONLY so
            the sensor works against the new source. Run the project's
            tests and the sensor itself and make both pass.
            TODO: name the sensor file and the exact test/run commands.

            Do NOT commit, push, or open a pull request — a follow-up job
            ships your working-tree change. Finish by writing three files
            into a repair-out/ directory in the workspace:
            - repair-out/branch — one line: fix/sensor-<new-source-host>
            - repair-out/title — one line, the PR title.
            - repair-out/body.md — the PR body: the evidence trail (chosen
              source, a trimmed sample of its real response, why it fits).
              No "Fixes #N" line; the ship job appends it.
      - name: Collect the repair artifact
        # TODO: replace sensor.mjs with your sensor file. The pathspec is the
        # mechanical write-surface constraint: edits to any other file do not
        # ship.
        run: |
          mkdir -p "$RUNNER_TEMP/repair-artifact"
          git diff -- sensor.mjs > "$RUNNER_TEMP/repair-artifact/sensor.patch"
          if [ ! -s "$RUNNER_TEMP/repair-artifact/sensor.patch" ]; then
            echo "::error::agent made no change to the sensor"
            exit 1
          fi
          for f in branch title body.md; do
            if [ ! -s "repair-out/$f" ]; then
              echo "::error::agent did not write repair-out/$f"
              exit 1
            fi
            cp "repair-out/$f" "$RUNNER_TEMP/repair-artifact/$f"
          done
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: sensor-repair-output
          path: \${{ runner.temp }}/repair-artifact
          if-no-files-found: error
          retention-days: 7

  ship:
    needs: repair
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: sensor-repair-output
          path: \${{ runner.temp }}/repair-artifact
      - name: Apply and verify the patch
        # TODO: replace sensor.mjs (twice) and \`node --test\` with your
        # sensor file and test command.
        run: |
          branch="$(head -n1 "$RUNNER_TEMP/repair-artifact/branch")"
          if ! printf '%s' "$branch" | grep -Eq '^fix/sensor-[A-Za-z0-9.-]+$'; then
            echo "::error::branch name does not match fix/sensor-<host>: $branch"
            exit 1
          fi
          echo "BRANCH=$branch" >> "$GITHUB_ENV"
          git apply --include=sensor.mjs "$RUNNER_TEMP/repair-artifact/sensor.patch"
          changed="$(git diff --name-only)"
          if [ "$changed" != "sensor.mjs" ]; then
            echo "::error::patch changed more than the sensor: $changed"
            exit 1
          fi
          node --test
      - name: Mint App installation token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: \${{ secrets.CONTINUOUS_RESEARCH_APP_ID }}
          private-key: \${{ secrets.CONTINUOUS_RESEARCH_APP_PRIVATE_KEY }}
          # Exactly what shipping needs; minted only after the agent exited.
          permission-contents: write
          permission-pull-requests: write
      - name: Push the fix branch and open or update the PR
        # TODO: replace the bot git identity with your App's
        # (<app-id>+<app-slug>[bot]@users.noreply.github.com), and
        # sensor.mjs with your sensor file.
        env:
          GH_TOKEN: \${{ steps.app-token.outputs.token }}
          ISSUE_NUMBER: \${{ github.event.issue.number || inputs.issue_number }}
        run: |
          title="$(head -n1 "$RUNNER_TEMP/repair-artifact/title")"
          body="$RUNNER_TEMP/repair-artifact/body.md"
          printf '\\nFixes #%s.\\n' "$ISSUE_NUMBER" >> "$body"
          git config user.name "your-app-slug[bot]"
          git config user.email "TODO+your-app-slug[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:\${GH_TOKEN}@github.com/\${GITHUB_REPOSITORY}.git"
          git checkout -B "$BRANCH"
          git add sensor.mjs
          git commit -m "$title"
          git push --force origin "$BRANCH"
          existing="$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
          if [ -n "$existing" ]; then
            gh pr edit "$existing" --title "$title" --body-file "$body"
          else
            gh pr create --head "$BRANCH" --title "$title" --body-file "$body"
          fi
`;

const INTERPRETATION_WORKFLOW = `---
description: "Interpretation step: write the impact declaration for a new data edition onto its data-PR"
on:
  pull_request:
    types: [opened, reopened]
  bots:
    # TODO: your GitHub App's slug — the author of the engine's data-PRs.
    - your-app-slug
engine:
  # Engine/model are per-instance choices. This pairing is proven against
  # free-tier quotas (~16–25 API requests per session; smaller "lite"-class
  # models below gemini-3.1-flash-lite have failed the harness protocol).
  id: gemini
  model: gemini-3.1-flash-lite
timeout-minutes: 15
permissions:
  contents: read
  pull-requests: read
safe-outputs:
  push-to-pull-request-branch:
    # The interpretation contract: the agent may touch ONLY the impact
    # declaration and the living findings doc. allowed-files is the binding
    # constraint; protected-files must be 'allowed' because .research/ is a
    # top-level dot-folder, which the default 'blocked' policy rejects even
    # for allowlisted paths.
    protected-files: allowed
    allowed-files:
      - ".research/impact/*.md"
      - "findings.md"
---

# Interpretation step

You are the **interpretation step** of a Continuous Research instance. A
data-PR proposing a new data edition has just been opened. Your job is to
write the **impact declaration**: what the new edition means for the existing
claims.

## Guard

First check the triggering pull request's labels. If it has no label starting
with \`data:\`, stop immediately and do nothing. Otherwise, the part after
\`data:\` is the **descriptor**.

## Read

Check out the PR's branch. Read:

1. TODO: the new edition's artifact(s) for this project — describe where the
   sensor/pipeline writes them, e.g. \`data/<source>/<descriptor>.json\`.
2. \`findings.md\` — the living prose. Each claim paragraph is followed by an
   invisible HTML-comment annotation. Its inner content has this form (the
   line in the file is wrapped as an HTML comment):

   \`\`\`text
   claim: <id> | backs: <result keys> | status: <status>
   \`\`\`

## Write

On the PR branch, make exactly two changes:

1. **Create \`.research/impact/<descriptor>.md\`** — the impact declaration:
   - **Prior claim** — quote the current claim and its status.
   - **What changed** — the new edition's values vs. the ones in the prose.
   - **Assessment** — one of **strengthened / weakened / overturned**, with a
     short justification. Distinguish one-off moves from real changes; do not
     overclaim.
   - **Revised claim** — the new claim text.
2. **Update \`findings.md\`** — replace the claim paragraph with the revised
   claim (keep the same claim id in the annotation; update the values, the
   edition reference, and the \`status\` field as assessed).

Keep the tone factual and appropriately hedged. Commit both files to the PR
branch with the message \`interpretation(<descriptor>): impact declaration\`.
`;

const COMMENT_RESOLUTION_WORKFLOW = `---
description: "Comment resolution: address a reviewer's /resolve request on a data-PR"
on:
  slash_command:
    name: resolve
engine:
  id: gemini
  model: gemini-3.1-flash-lite
timeout-minutes: 15
permissions:
  contents: read
  pull-requests: read
safe-outputs:
  push-to-pull-request-branch:
    # Same contract as interpretation: the agent may touch ONLY the impact
    # declarations and the living findings doc.
    protected-files: allowed
    allowed-files:
      - ".research/impact/*.md"
      - "findings.md"
  add-comment:
    max: 1
---

# Comment resolution

You are the **comment-resolution step** of a Continuous Research instance. A
reviewer commented \`/resolve <request>\` on a pull request. Address their
request with changes on the PR branch, or explain why you can't.

## Guard

Check the pull request's labels. If this is not a pull request, or it has no
label starting with \`data:\`, reply (add-comment) that \`/resolve\` only
applies to data-PRs, and stop. Otherwise the part after \`data:\` is the
**descriptor**.

## The request

The reviewer's comment (sanitized) is:

> \${{ steps.sanitized.outputs.text }}

The request is everything after \`/resolve\`. The reviewer is asking for a
change to the edition's **interpretation** — e.g. rephrase or re-hedge a
claim, correct an arithmetic slip, expand the impact declaration's
justification, or reconcile the findings text with the edition artifact.
TODO: describe where this project's edition artifacts live.

## Act

- If the request concerns \`.research/impact/<descriptor>.md\` or
  \`findings.md\`: make the requested change on the PR branch, keeping the
  claim annotation format intact, commit with the message
  \`resolve(<descriptor>): <short summary>\`, and push via
  push_to_pull_request_branch.
- If the request is outside those two files, or asks for something factually
  unsupported by the edition artifact, do NOT force a change — reply
  explaining what you can and cannot do, and why.

## Reply

Always finish with one add-comment reply summarizing what you changed (or why
you made no change). Keep the tone factual and appropriately hedged.
`;

export const NEXT_STEPS = `
Next steps:
  1. Sensor: point .research/config.json "sensor" at a command that prints a
     detection-result JSON on stdout, and writes artifacts to the working tree.
  2. GitHub App (required): create an App (permissions: Contents, Issues, and
     Pull requests — read & write), install it on this repo, and set the
     CONTINUOUS_RESEARCH_APP_ID + CONTINUOUS_RESEARCH_APP_PRIVATE_KEY
     secrets. Data-PRs must be App-authored, or the interpretation workflow
     never triggers.
  3. Agent workflows: fill in the TODOs in
     .github/workflows/interpretation.md and comment-resolution.md, set your
     inference secret (e.g. GEMINI_API_KEY), then compile them:
       gh extension install github/gh-aw && gh aw compile
  4. Commit .research/ and .github/workflows/ (including the compiled
     interpretation.lock.yml), then dispatch the "sense" workflow.
  5. Site (optional): set site.enabled + title in .research/config.json,
     enable GitHub Pages (source: GitHub Actions), and dispatch the "site"
     workflow.
  6. Sensor repair (optional, Claude Code): if you keep
     .github/workflows/sensor-repair.yml, set CLAUDE_CODE_OAUTH_TOKEN and
     fill in its TODOs (app slug, sensor file, candidate sources); your
     sensor must write .research/drift/report.json when it cannot produce
     an edition. Delete the file to opt out.
`;

export function scaffoldFiles(): ScaffoldFile[] {
  return [
    { path: ".research/config.json", content: CONFIG },
    { path: ".github/workflows/sense.yml", content: SENSE_WORKFLOW },
    { path: ".github/workflows/decline.yml", content: DECLINE_WORKFLOW },
    { path: ".github/workflows/site.yml", content: SITE_WORKFLOW },
    { path: ".github/workflows/sensor-repair.yml", content: SENSOR_REPAIR_WORKFLOW },
    { path: ".github/workflows/interpretation.md", content: INTERPRETATION_WORKFLOW },
    { path: ".github/workflows/comment-resolution.md", content: COMMENT_RESOLUTION_WORKFLOW },
  ];
}
